services:
  krs-extension:
    image: kubetoolsca/krs-docker-extension:0.0.3
    hostname: krs-extension
    ports:
      - 4999:3986
      - 3987:3987
      - 57681:7681
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock



